name: Add coverage comment on PR

on:
  workflow_run:
    workflows: ["Test and lint"]
    types:
      - completed
      
permissions: {}

jobs:
  cov-report:
    permissions:
        contents: read
        pull-requests: write
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request'
    steps:
      - name: Get PR number
        id: get_pr_number
        run: |
          PR_DATA=$(curl -s https://api.github.com/search/issues?q=repo:${{github.repository}}+type:pr+sha:${{github.event.workflow_run.head_sha}} | jq -c '.')
          ITEMS_COUNT=$(jq '.items | length' <<< "$PR_DATA")
          # Check if head commit is on a single PR else ambiguous which PR triggered the workflow
          if [ "$ITEMS_COUNT" -ne 1 ]; then
            echo "Error: Expected exactly one PR, but found $ITEMS_COUNT." >&2
            exit 1
          fi
          PR_NUMBER=$(jq '.items[0].number' <<< "$PR_DATA")
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage.xml
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Check PR and file
        continue-on-error: true
        run: |
          echo "PR_NUMBER=${{ steps.get_pr_number.outputs.pr_number }}"
          ls 
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '80 90'
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728  # v2.9.3
        with:
          recreate: true
          path: code-coverage-results.md
          number: ${{ steps.get_pr_number.outputs.pr_number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
